# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cld < Formula
  desc "An unofficial CLI for Cloudinary"
  homepage "https://github.com/martinsirbe/go-cloudinary"
  version "0.0.0"

  on_macos do
    url "https://github.com/martinsirbe/go-cloudinary/releases/download/v0.0.0/cld_0.0.0_darwin_all.tar.gz"
    sha256 "6f9a96fa7b53cdb2b083ae0b09ff7464dd076773b048ecec8c3083b29578742f"

    def install
      bin.install "cld"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/martinsirbe/go-cloudinary/releases/download/v0.0.0/cld_0.0.0_linux_amd64.tar.gz"
        sha256 "abc4d328f16a095f626f0519d0018b4a39818e67ff9cf0bea6cd534d2d20c38a"

        def install
          bin.install "cld"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/martinsirbe/go-cloudinary/releases/download/v0.0.0/cld_0.0.0_linux_arm64.tar.gz"
        sha256 "5e0548bce9e1880520b2c0450c761a86ac0dcb4b8b59f1b0e55f258ed3b58cc6"

        def install
          bin.install "cld"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing the Cloudinary CLI (cld)!

      The `CLOUDINARY_URL` environment variable is mandatory. Set it before using cld:
      `export CLOUDINARY_URL=cloudinary://api_key:api_secret@my_cloud_name`
    EOS
  end

  test do
    system "#{bin}/cld", "--help"
  end
end
