# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cld < Formula
  desc "An unofficial CLI for Cloudinary"
  homepage "https://github.com/martinsirbe/go-cloudinary"
  version "0.0.2"

  on_macos do
    url "https://github.com/martinsirbe/go-cloudinary/releases/download/v0.0.2/cld_0.0.2_darwin_all.tar.gz"
    sha256 "b17b038580901d35e495bc27faa3bdce8c7d54bd81f271c1c1243ece1cb50017"

    def install
      bin.install "cld"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/martinsirbe/go-cloudinary/releases/download/v0.0.2/cld_0.0.2_linux_amd64.tar.gz"
        sha256 "2d119b800ec1ffeb00a9a2f2c74f1c42eb8a427aae4f7a6e4a1c26269438f781"

        def install
          bin.install "cld"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/martinsirbe/go-cloudinary/releases/download/v0.0.2/cld_0.0.2_linux_arm64.tar.gz"
        sha256 "82e8272b9ac33ea5006b139c030dea7c1da2e60f411108d7868b1313b1f2c63c"

        def install
          bin.install "cld"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing the Cloudinary CLI (cld)!

      The `CLOUDINARY_URL` environment variable is mandatory. Set it before using cld:
      `export CLOUDINARY_URL=cloudinary://api_key:api_secret@my_cloud_name`
    EOS
  end

  test do
    system "#{bin}/cld", "--help"
  end
end
