# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Genid < Formula
  desc "Generate Unique IDs"
  homepage "https://github.com/martinsirbe/genid"
  version "0.0.1"

  on_macos do
    url "https://github.com/martinsirbe/genid/releases/download/v0.0.1/genid_0.0.1_darwin_all.tar.gz"
    sha256 "336881e2d9f13e5f7ee35d4856252f8800e62c4c2e8e271299bccec518202cfb"

    def install
      bin.install "genid"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/martinsirbe/genid/releases/download/v0.0.1/genid_0.0.1_linux_amd64.tar.gz"
      sha256 "afab9371d7b40f0aa6fd821b436cf11e3bc3027d99f1fc7a44ecd02ac7536c05"
      def install
        bin.install "genid"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/martinsirbe/genid/releases/download/v0.0.1/genid_0.0.1_linux_arm64.tar.gz"
      sha256 "69bdb525b405677be1b80a543a400d06d8efaa744b174026a67e3edf39caa18c"
      def install
        bin.install "genid"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing the Unique ID Generator (genid)! Here are some tips to get started:

      ## Usage

      - Run `genid` from any terminal to generate unique identifiers instantly.
      - Specify the ID format using the `-type` flag (e.g. `-type uuid4`, `-type ulid`, etc.).
      - Generate multiple IDs at once using the `-n` flag.
      - For NanoID, you can customise the output length with the `-len` flag.

      ## Supported ID Types

      - `ulid`: Lexicographically sortable identifier
      - `uuid4`: Random UUID
      - `uuid5`: Name-based UUID (SHA-1)
      - `uuid6`: Reordered time-based UUID
      - `uuid7`: Unix epoch time-based UUID
      - `ksuid`: K-Sortable unique ID
      - `xid`: MongoDB-style unique ID
      - `nanoid`: Compact, URL-safe unique ID
      - `snowflake`: Twitter-style time-based ID

      ## Integration Ideas

      - **Shell Scripts**: Use `genid` to generate test IDs or stable primary keys during automation.
      - **Terminals**: Pipe output directly into tools like `jq`, `xargs`, or `pbcopy` for fast development workflows.
      - **Debugging & Prototyping**: Quickly generate realistic IDs in your backend services or data pipelines.

      To learn more about options, run `genid --help` or visit the GitHub repository:
      https://github.com/martinsirbe/genid

      Happy ID generating!
    EOS
  end

  test do
    system "#{bin}/genid", "--help"
  end
end
