# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yp < Formula
  desc "Year Progress Indicator"
  homepage "https://github.com/martinsirbe/go-year-progress"
  version "0.1.3"

  on_macos do
    url "https://github.com/martinsirbe/go-year-progress/releases/download/v0.1.3/yp_0.1.3_darwin_all.tar.gz"
    sha256 "ec1fe68c3096b5bea11d412634f86e5a589099cd040d01c5d4f07b0dcb6e9046"

    def install
      bin.install "yp"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/martinsirbe/go-year-progress/releases/download/v0.1.3/yp_0.1.3_linux_amd64.tar.gz"
      sha256 "8d9ab9e85270e0529a6b886501bf421bc093d66da8ef8b6326e976bf9d4f4ffb"
      def install
        bin.install "yp"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/martinsirbe/go-year-progress/releases/download/v0.1.3/yp_0.1.3_linux_arm64.tar.gz"
      sha256 "c54dd90a3df9ad7233b76a921e11365bad2c5b712d85c3ac2722b2c0597ee3f6"
      def install
        bin.install "yp"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing the Year Progress Indicator (yp)! Here are some tips to get started:

      ## Configuration and Usage

      - Run `yp` in any terminal to see how much of the current year has elapsed, represented through a visually appealing progress bar.
      - Customise the appearance of your progress bar with CLI options or environment variables for a personalized touch:
        - Use CLI options like `--location` to set your timezone or `--total-blocks` to adjust the progress bar's length.
        - Alternatively, set environment variables such as `YP_LOCATION` and `YP_TOTAL_BLOCKS` for persistent configurations.

      ## Integration Ideas

      - **Terminal Welcome Message**: Enhance your terminal sessions by adding `yp` to your shell's profile (e.g., `.bashrc`, `.zshrc`), so you can visualize the year's progress with every new terminal window.
      - **GitHub README**: Make your project README stand out by including the year's progress bar.
      - **Daily Logs/Journals**: Incorporate the progress bar in your digital or printed logs as a unique way to track the passage of time.
      - **Personal Websites**: Share the year's progression with visitors by integrating the tool's output into your site.

      For more details on options and configurations, run `yp --help` or check the GitHub repository: https://github.com/martinsirbe/yp

      Enjoy visualising the passage of time with yp, and feel free to contribute to its development!
    EOS
  end

  test do
    system "#{bin}/yp", "--help"
  end
end
