# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yp < Formula
  desc "Year Progress Indicator"
  homepage "https://github.com/martinsirbe/go-year-progress"
  version "0.1.0"

  on_macos do
    url "https://github.com/martinsirbe/go-year-progress/releases/download/v0.1.0/yp_0.1.0_darwin_all.tar.gz"
    sha256 "4d14e313a3b774a51508b6760e0f2108268c22ae0aacd50fdab2756b4dd11e88"

    def install
      bin.install "yp"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/martinsirbe/go-year-progress/releases/download/v0.1.0/yp_0.1.0_linux_arm64.tar.gz"
      sha256 "2fe6911ddbefaf51c60f104741639960793075041998aa6808ab9716600c6ca5"

      def install
        bin.install "yp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/martinsirbe/go-year-progress/releases/download/v0.1.0/yp_0.1.0_linux_amd64.tar.gz"
      sha256 "8af40c72dd3f8448b1f8cf1123dedcca55aad3436b167efb5ce39384f7e7dec5"

      def install
        bin.install "yp"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing the Year Progress Indicator (yp)! Here are some tips to get started:

      ## Configuration and Usage

      - Run `yp` in any terminal to see how much of the current year has elapsed, represented through a visually appealing progress bar.
      - Customise the appearance of your progress bar with CLI options or environment variables for a personalized touch:
        - Use CLI options like `--location` to set your timezone or `--total-blocks` to adjust the progress bar's length.
        - Alternatively, set environment variables such as `YP_LOCATION` and `YP_TOTAL_BLOCKS` for persistent configurations.

      ## Integration Ideas

      - **Terminal Welcome Message**: Enhance your terminal sessions by adding `yp` to your shell's profile (e.g., `.bashrc`, `.zshrc`), so you can visualize the year's progress with every new terminal window.
      - **GitHub README**: Make your project README stand out by including the year's progress bar.
      - **Daily Logs/Journals**: Incorporate the progress bar in your digital or printed logs as a unique way to track the passage of time.
      - **Personal Websites**: Share the year's progression with visitors by integrating the tool's output into your site.

      For more details on options and configurations, run `yp --help` or check the GitHub repository: https://github.com/martinsirbe/yp

      Enjoy visualising the passage of time with yp, and feel free to contribute to its development!
    EOS
  end

  test do
    system "#{bin}/yp", "--help"
  end
end
