# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yp < Formula
  desc "Year Progress Indicator"
  homepage "https://github.com/martinsirbe/go-year-progress"
  version "0.1.2"

  on_macos do
    url "https://github.com/martinsirbe/go-year-progress/releases/download/v0.1.2/yp_0.1.2_darwin_all.tar.gz"
    sha256 "c72f8450515d1135bf7c71801999e7f1e326e882061530e83cfd4b63d41a3582"

    def install
      bin.install "yp"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/martinsirbe/go-year-progress/releases/download/v0.1.2/yp_0.1.2_linux_amd64.tar.gz"
        sha256 "ec56bd4564227c497c4f6716bc07607b8de5adba00c3545d8a2e40f0aa1ec9e8"

        def install
          bin.install "yp"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/martinsirbe/go-year-progress/releases/download/v0.1.2/yp_0.1.2_linux_arm64.tar.gz"
        sha256 "9ad75615a8f42e5d3598eea995b646e94e5ae20ca9d9f9ba9869914862d3a4c2"

        def install
          bin.install "yp"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing the Year Progress Indicator (yp)! Here are some tips to get started:

      ## Configuration and Usage

      - Run `yp` in any terminal to see how much of the current year has elapsed, represented through a visually appealing progress bar.
      - Customise the appearance of your progress bar with CLI options or environment variables for a personalized touch:
        - Use CLI options like `--location` to set your timezone or `--total-blocks` to adjust the progress bar's length.
        - Alternatively, set environment variables such as `YP_LOCATION` and `YP_TOTAL_BLOCKS` for persistent configurations.

      ## Integration Ideas

      - **Terminal Welcome Message**: Enhance your terminal sessions by adding `yp` to your shell's profile (e.g., `.bashrc`, `.zshrc`), so you can visualize the year's progress with every new terminal window.
      - **GitHub README**: Make your project README stand out by including the year's progress bar.
      - **Daily Logs/Journals**: Incorporate the progress bar in your digital or printed logs as a unique way to track the passage of time.
      - **Personal Websites**: Share the year's progression with visitors by integrating the tool's output into your site.

      For more details on options and configurations, run `yp --help` or check the GitHub repository: https://github.com/martinsirbe/yp

      Enjoy visualising the passage of time with yp, and feel free to contribute to its development!
    EOS
  end

  test do
    system "#{bin}/yp", "--help"
  end
end
